// <auto-generated />
using System;
using TPCT_TPH_TPT.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TPCT_TPH_TPT.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPCT_TPH_TPT.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TPCT_TPH_TPT.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("TPCT_TPH_TPT.Models.Employee");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("TPCT_TPH_TPT.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("TPCT_TPH_TPT.Models.Employee");

                    b.Property<int>("CountOfHours")
                        .HasColumnType("int");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("TPCT_TPH_TPT.Models.FullTimeEmployee", b =>
                {
                    b.HasOne("TPCT_TPH_TPT.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("TPCT_TPH_TPT.Models.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPCT_TPH_TPT.Models.PartTimeEmployee", b =>
                {
                    b.HasOne("TPCT_TPH_TPT.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("TPCT_TPH_TPT.Models.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
